---
# tasks file for ckan
- name: Yum install any CKAN dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    # needed to install psycopg2
    - postgresql-devel
    - postgresql-libs
    - libselinux-python
    # needed if installing ldap-based authentication
    - python-ldap
  sudo: yes

- name: create CKAN directory
  file:
    path="{{ckan_install_dir}}"
    state=directory
    owner="{{ckan_user}}"
    group="{{ckan_group}}"
    mode=0755
    recurse=yes
  sudo: yes

- name: pip install CKAN
  pip: 
    name="git+https://github.com/ckan/ckan.git@{{ckan_version_tag}}#egg=ckan"
    virtualenv="{{ckan_venv}}"
    virtualenv_site_packages=no
    extra_args="-e"
  environment: 
    # Depending on the user running this command, we need
    # to ensure /usr/local/bin is in the path so that 
    # virtualenv is accessible.  
    PATH: /usr/local/bin:/bin:/usr/bin
  sudo: yes

- name: pip install CKAN requirements
  pip:
    requirements="{{ckan_venv}}/src/ckan/requirements.txt"
    virtualenv="{{ckan_venv}}"
  environment: 
    # This is a bit of a hack so that we don't have to spend
    # time gathering facts. We could just use anisble_env.PATH
    PATH: /usr/pgsql-9.3/bin:/usr/local/bin:/bin:/usr/bin
  sudo: yes

# TODO: Write a custom module that installs the custom plugins
- name: pip install CKAN any custom plugins
  pip: 
    name="git+{{item.url}}#egg={{item.egg_name}}"
    virtualenv="{{ckan_venv}}"
    virtualenv_site_packages=no
    extra_args="-e"
  with_items: ckan_custom_plugins
  when: ckan_custom_plugins is defined
  sudo: yes

- name: check if custom plugin has requirements.txt file
  stat: path="{{ckan_venv}}/src/{{item.egg_name|regex_replace('_', '-')}}/requirements.txt"
  with_items: ckan_custom_plugins
  when: ckan_custom_plugins is defined
  register: plugins_requirements
  sudo: yes

- name: pip install the requirements of custom plugins
  pip:
    requirements="{{ckan_venv}}/src/{{item.item.egg_name|regex_replace('_', '-')}}/requirements.txt"
    virtualenv="{{ckan_venv}}"
  with_items: plugins_requirements.results
  when: item.stat.exists
  sudo: yes

- name: create CKAN config directory
  file:
    path="{{ckan_config_dir}}"
    state=directory
    owner="{{ckan_user}}"
    group="{{ckan_group}}"
  sudo: yes

- name: create CKAN uploads directory
  file:
    path="{{ckan_file_storage_dir}}"
    state=directory
    owner="{{ckan_user}}"
    group="{{ckan_group}}"
  sudo: yes

- name: create CKAN log directory
  file:
    path="{{ckan_log_dir}}"
    state=directory
    owner="{{ckan_user}}"
    group="{{ckan_group}}"
  sudo: yes

- name: create CKAN config file
  template: 
    src="config.ini.j2"
    dest="{{ckan_config_dir}}/config.ini"
  notify: restart apache
  sudo: yes

- name: set read-only ckan user
  shell: source {{ckan_venv}}/bin/activate && paster --plugin=ckan datastore set-permissions -c {{ckan_config_dir}}/config.ini | sudo -u postgres psql --set ON_ERROR_STOP=1
    chdir="{{ckan_venv}}/src/ckan"
  when: groups.has_key('local') and inventory_hostname in groups.local
  #when: create_datastore_db|changed or create_datastore_db_user|changed or create_ckan_db|changed or create_ckan_db_user|changed
  notify: restart postgres
  sudo: yes

- name: create CKAN tables in database
  shell: source {{ckan_venv}}/bin/activate && paster db init -c {{ckan_config_dir}}/config.ini
    chdir="{{ckan_venv}}/src/ckan"
  sudo: yes
  #sudo_user: postgres
  #when: create_datastore_db|changed or create_datastore_db_user|changed or create_ckan_db|changed or create_ckan_db_user|changed
  notify: restart postgres

- name: create symlink to who.ini
  file: 
    src={{ckan_venv}}/src/ckan/who.ini
    dest=/etc/ckan/default/who.ini
    state=link
  sudo: yes

- name: create CKAN wsgi file
  template: 
    src="apache.wsgi.j2"
    dest="{{ckan_config_dir}}/apache.wsgi"
    mode=0755
  notify: restart apache
  sudo: yes

- name: create CKAN apache config file
  template:
    src="ckan.conf.j2"
    dest="/etc/httpd/conf.d/ckan.conf"
  sudo: yes
  notify: restart apache

- name: ensure correct ownership for all ckan directories
  file:
      path="{{item}}"
      state=directory
      owner="{{ckan_user}}"
      group="{{ckan_group}}"
      recurse=true
  with_items:
    - "{{ckan_install_dir}}"
    - "{{ckan_config_dir}}"
    - "{{ckan_log_dir}}"
  notify: restart apache
  sudo: yes

- name: create crontab for sending activity stream emails
  cron: name="ckan_send_emails"
        minute={{ckan_email_flush_interval}}
        job="echo $(date) >> {{ckan_log_dir}}/email_flush.log && echo '{}' | {{ckan_venv}}/bin/paster post -c {{ckan_config_dir}}/config.ini /api/action/send_email_notifications >> {{ckan_log_dir}}/email_flush.log && echo '' >> {{ckan_log_dir}}/email_flush.log"
        user=root
  sudo: yes